import { Lexend } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/nav/NavigationBar";

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
});

export const metadata = {
  title: "Whitworth Life",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lexend.variable}>
        <NavigationBar />
        <main style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>{children}</main>
        <footer className="w-full h-24 flex items-center justify-center border-t mt-8">
          <p className="text-center">
            Made by{" "}
            <a className="underline" href="https://ilkeeren.dev">
              Eren
            </a>{" "}
            with ❤️
          </p>
        </footer>
      </body>
    </html>
  );
}
