import { Lexend } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/nav/NavigationBar";

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
});

export const metadata = {
  title: "Whitworth Life",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lexend.variable}>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
